# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a906a18cfb12c885f2009f0ff29c363c6a02a266451f6b13482af894e686a6e6ea7129961b49bd2698252f76c7ad12f660dcd111ff3507afee97d9bc1d012675
  user: radmin
  password: hvatit
test:
  secret_key_base: 9a6b6e68cad13115703bc6ba1675d5545a0e5e8b1583f221492d8edde9943868b18a02b04ae323b79264acfaebf4a528309684e22aa08285f2456fa9dcba580c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  user: svoyadoskateam
  password: hva414pLSst0p14

